=== camila-lopez08/xml-Ejercicio6/src/Ejercicio6.dtd
<?xml version="1.0" enconding="UTF-8"?>
<!DOCTYPE listacursos SYSTEM  "Ejercicio6.xml">
<!DOCTYPE listacursos[
<!ELEMENT listacursos (curso)+>
        <!ELEMENT curso (alumno)+>
        <!ELEMENT alumno (dni, nombre,
                apellido1, apellido2?, listaasignaturas)>

        <!ELEMENT listaasignaturas (asignatura+)>
        <!ELEMENT asignatura (nombre, profesor)>
        <!ATTLIST asignatura codigo CDATA #REQUIRED>

        <!ELEMENT profesor (nrp, nombre, apellido1, apellido2?)>

        <!ELEMENT dni    (#PCDATA)>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT apellido1    (#PCDATA)>
        <!ELEMENT apellido2    (#PCDATA)>
        <!ELEMENT nrp    (#PCDATA)>
        ]

=== camila-lopez08/xml-Ejercicio6/src/Ejercicio6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listacursos SYSTEM  "Ejercicio6.dtd">
<listacursos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="Ejercicio6.xsd">

    <curso>
        <alumno>
            <dni>e-1000872026</dni>
            <nombre>camila</nombre>
            <apellido1>lopez</apellido1>
            <listaasignaturas>
                <asignatura codigo="23201">
                    <nombre>Sistemas Operativos</nombre>
                    <profesor>
                        <nrp>4</nrp>
                        <nombre>Carlos</nombre>
                        <apellido1>Builes</apellido1>
                    </profesor>
                </asignatura>
            </listaasignaturas>
        </alumno>
    </curso>
    <curso>
        <alumno>
            <dni>e-1000872026</dni>
            <nombre>camila</nombre>
            <apellido1>lopez</apellido1>
            <apellido2>Gutierrez</apellido2>
            <listaasignaturas>
                <asignatura codigo="23201">
                    <nombre>Sistemas Operativos</nombre>
                    <profesor>
                        <nrp>4</nrp>
                        <nombre>Carlos</nombre>
                        <apellido1>Builes</apellido1>
                    </profesor>
                </asignatura>
            </listaasignaturas>
        </alumno>
    </curso>
</listacursos>
